Vagrant.configure("2") do |config|  
  config.vm.box = "centos/7"
  config.disksize.size = "120GB"
  config.vm.network "public_network", type: "dhcp", bridge: "enp2s0"
  config.vm.host_name = "centos.nisiafloresta.rn"
  config.vm.provision "shell", path: "/home/felipe/scripts/startup.sh"
  config.vm.provider "virtualbox" do |vbx|
    vbx.name = "Centos-7"
    vbx.gui = true
    vbx.memory = "1024"
    vbx.cpus = "2"
  end
end
